import React from 'react'

export const locStrings = {
  ru: {
    contacts: "Контакты",
    registration: "Регистрация",
    login: "Войти",
    planYourTrip: <div><b>Планируйте</b> <span>свою поездку заранее!</span></div>,
    buyTickets: "Купить билеты",
    news: "Новости",
    internTravel: "Международные поездки",
    suburbanTravel: "Пригородные поездки",
    dicsounts: "скидки",
    whence: "Откуда",
    where: "Куда",
    from: "от",
    to: "до",
    search: "Искать",
    platzcard: "Плацкарт",
    coupe: "Купэ",
    lux: "Люкс",
    passengers: "Пассажиры",
    find: "Поиск",
    oneway: "В одну сторону",
    roundtrip: "Туда и обратно",
    multiTrip: "Мульти поездка",
    addRoute: "Добавить маршрут",
    previous: "Предыдущее",
    next: "Следующий",
    trainSchedule: "Расписание движение поездов",
    departures: "Отправления",
    arrivals: "Прибытия",
    departuresShort: "Отпр",
    way: "Путь",
    delay: "Опозд.",
    arrivalsShort: "Приб",
    ticketsLabel: "Железнодорожные билеты",
    bestDeals: "Лучшие предложения",
    more: "Подробнее",
    popDestinations: "Популярные маршруты",
    chooseNextTrip: "Выберите свое следующее путешествие",
    forum: "Форум",
    aboutUs: "О компании",
    help: "Помощь",
    howToPlaceAnOrder: "Как оформить заказ",
    howTpPayForAnOrder: "Как оплатить заказ",
    getTicketProcedure: "Процедура получения билетов",
    ticketReturn: "Возврат билетов",
    infoForPass: "Информация для пассажиров",
    userPolicy: "Правила пользователя",
    addressInfo: "ул. Сыгынак 29, Астана",
    mobile: "Мобильный",
    contactUs: "Свяжитесь с нами",
    send: "Отправить",
    message: "Сообщение",
    copyright: "@2015 Treno.kz. ЖД билеты. Отзывы на",
    name: "Имя",
    passConfirm: "Повторите пароль",
    email: "Email",
    lastName: "Фамилия",
    password: "Пароль",
    captcha: "Введите надпись с картинки",
    required: <p>Поля отмечанные <span className="red">*</span> обязательны для заполнения!</p>,
    register: "Зарегистрироваться",
    all: "Все",
    popularNews: "Популярные новости",
    foreignNews: "Зарубежные новости",
    newsOfTheDay: "Новость дня от treno.kz",
    read: "Читать",
    hello: "Добро пожаловать!",
  },
  kz: {
    contacts: "Бізбен байланысыңыз",
    registration: "Тіркеу формасы",
    login: "Жүйеге кіріңіз",
    planYourTrip: <div><span>Сіздің сапарыңызды алдын ала</span> <b>жоспарлаңыз</b></div>,
    buyTickets: "Билеттерді сатып алыңыз",
    news: "Жаңалықтар",
    internTravel: "Халықаралық саяхат",
    suburbanTravel: "Қала маңындағы саяхат",
    dicsounts: "жеңілдіктер",
    whence: "Орналасуы",
    where: "Қайда",
    from: "бастап",
    to: "дейін",
    search: "Іздеу",
    platzcard: "Плацкарт",
    coupe: "Купе",
    lux: "Люкс",
    passengers: "Жолаушылар",
    find: "Іздеу",
    oneway: "Бір жолы",
    roundtrip: "Онда және артында",
    multiTrip: "Бірнеше сапар",
    addRoute: "Бағытты қосыңыз",
    previous: "Алдыңғы",
    next: "Келесі",
    trainSchedule: "Пойыз кестесі",
    departures: "Ұшулар",
    arrivals: "Келу",
    departuresShort: "Ұшу",
    way: "Жол",
    delay: "Кешік.",
    arrivalsShort: "Келу",
    ticketsLabel: "Темір жол билеттері",
    bestDeals: "Үздік ұсыныстар",
    more: "Көбірек біліңіз",
    popDestinations: "Танымал маршруттар",
    chooseNextTrip: "Келесі сапарыңызды таңдаңыз",
    forum: "Форум",
    aboutUs: "Компания туралы",
    help: "Көмек",
    howToPlaceAnOrder: "Тапсырысты қалай орналастыру керек",
    howTpPayForAnOrder: "Тапсырысты төлеу әдісі",
    getTicketProcedure: "Билеттерді алу тәртібі",
    ticketReturn: "Билеттерді қайтарыңыз",
    infoForPass: "Жолаушыларға арналған ақпарат",
    userPolicy: "Пайдаланушы саясаты",
    addressInfo: "Сығанақ 29, Астана қ",
    mobile: "Ұялы телефон",
    contactUs: "Бізбен байланысыңыз",
    send: "Жіберу",
    message: "Сіздің хабарламаңыз",
    copyright: "@ 2015 Treno.kz. ЖД билеттер. Пікірлер үшін",
    name: "Аты",
    passConfirm: "Құпия сөзді қайталаңыз",
    email: "Email",
    lastName: "Жөні",
    password: "Құпия сөз",
    captcha: "Суреттен тақырыпты енгізіңіз",
    required: <p>Белгіленген өрістер <span className="red">*</span> міндетті!</p>,
    register: "Тіркелу",
    all: "Барлығы",
    popularNews: "Танымал жаңалықтар",
    foreignNews: "Шетелдік жаңалықтар",
    newsOfTheDay: "Күннің жаңалықтары treno.kz",
    read: "Оқылды",
    hello: "Қош келдіңіз!",
  },
  en: {
    contacts: "Contacts",
    registration: "Registration",
    login: "Log In",
    planYourTrip: <div><b>Plan</b> <span>your trip in advance!</span></div>,
    buyTickets: "Get tickets",
    news: "News",
    internTravel: "International travel",
    suburbanTravel: "Suburban travel",
    dicsounts: "Discounts",
    whence: "From",
    where: "To",
    from: "from",
    to: "to",
    search: "Search",
    platzcard: "Platzcard",
    coupe: "Coupe",
    lux: "Lux",
    passengers: "Passengers",
    find: "Search",
    oneway: "One way",
    roundtrip: "Roundtrip",
    multiTrip: "Multi-trip",
    addRoute: "Add a route",
    previous: "Previous",
    next: "Next",
    trainSchedule: "Train timetable",
    departures: "Departures",
    arrivals: "Arrivals",
    departuresShort: "Dep",
    way: "Way",
    delay: "Delay",
    arrivalsShort: "Arr",
    ticketsLabel: "Railway tickets",
    bestDeals: "Best deals",
    more: "More",
    popDestinations: "Popular destinations",
    chooseNextTrip: "Choose your next trip",
    forum: "Forum",
    aboutUs: "About company",
    help: "Help",
    howToPlaceAnOrder: "How to place an order",
    howTpPayForAnOrder: "How to pay for an order",
    getTicketProcedure: "Procedure for obtaining tickets",
    ticketReturn: "Return tickets",
    infoForPass: "Information for passengers",
    userPolicy: "User Policy",
    addressInfo: "Syganak st. 29, Astana",
    mobile: "Mobile",
    contactUs: "Contact Us",
    send: "Send",
    message: "Message",
    copyright: "@ 2015 Treno.kz. Train tickets. Reviews for",
    name: "Name",
    passConfirm: "Confirm password",
    email: "Email",
    lastName: "Surname",
    password: "Password",
    captcha: "Enter the caption from the image",
    required: <p>Fields marked <span className="red">*</span> are required!</p>,
    register: "Sign Up",
    all: "All",
    popularNews: "Popular news",
    foreignNews: "Foreign news",
    newsOfTheDay: "News of the day from treno.kz",
    read: "Read",
    hello: "Welcome!",
  }
}
